[project_id]
project_id = "tcrmlhfsroyhaxdfwyll"

[functions.ipsrs-api]
verify_jwt = true

[functions.ipsrs-link-account]
verify_jwt = true

[functions.ipsrs-auth-bridge]
verify_jwt = false

[functions.ipsrs-bulk-provision-once]
verify_jwt = true
