/* Panel Hak Akses — hanya muncul untuk KA IPSRS. */
(function(){
  let mounted=false, staffCache=[];
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  async function callAccessApi(action,...args){
    if(typeof authRun!=='function') throw new Error('API Supabase belum siap.');
    return authRun(action,...args);
  }
  async function callAccessRead(action){
    if(typeof authRun!=='function') throw new Error('API Supabase belum siap.');
    return authRun(action);
  }
  function mount(){
    if(mounted||typeof getSession!=='function')return;
    const s=getSession();
    if(!s||s.role!=='KA_IPSRS')return;
    mounted=true;
    const style=document.createElement('style');style.textContent=`#accessBtn{position:fixed;right:22px;bottom:22px;z-index:8000;border:0;border-radius:14px;padding:12px 16px;font-weight:700;cursor:pointer;box-shadow:0 8px 24px rgba(0,0,0,.18)}#accessBg{display:none;position:fixed;inset:0;background:rgba(15,23,42,.48);z-index:9000;align-items:center;justify-content:center;padding:18px}#accessBg.show{display:flex}.access-modal{background:#fff;border-radius:20px;width:min(920px,100%);max-height:90vh;overflow:auto;box-shadow:0 24px 70px rgba(0,0,0,.25);padding:24px}.access-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.access-head h2{margin:0 0 5px}.access-muted{color:#64748b;font-size:13px}.access-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:20px 0}.access-card{border:1px solid #e2e8f0;border-radius:14px;padding:16px}.access-card h3{margin:0 0 6px;font-size:15px}.access-row{display:flex;justify-content:space-between;align-items:center;gap:12px}.access-switch{width:48px;height:26px;border-radius:20px;border:0;background:#cbd5e1;position:relative;cursor:pointer}.access-switch.on{background:#16a34a}.access-switch:after{content:'';position:absolute;width:20px;height:20px;background:#fff;border-radius:50%;top:3px;left:4px;transition:.15s}.access-switch.on:after{left:24px}.access-form{display:grid;grid-template-columns:1fr 1fr auto;gap:10px;align-items:end;margin-top:14px}.access-form label{font-size:12px;font-weight:700;color:#475569}.access-form select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:10px;background:#fff}.access-table{width:100%;border-collapse:collapse;margin-top:16px;font-size:13px}.access-table th,.access-table td{padding:10px;border-bottom:1px solid #e2e8f0;text-align:left}.access-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:20px}.access-btn-secondary{border:1px solid #cbd5e1;background:#fff;border-radius:10px;padding:10px 14px;cursor:pointer}.access-btn-primary{border:0;border-radius:10px;padding:10px 14px;font-weight:700;cursor:pointer}@media(max-width:700px){.access-grid,.access-form{grid-template-columns:1fr}.access-modal{padding:18px}.access-table{font-size:12px;display:block;overflow:auto;white-space:nowrap}}`;document.head.appendChild(style);
    const btn=document.createElement('button');btn.id='accessBtn';btn.textContent='⚙ Hak Akses';btn.onclick=open;document.body.appendChild(btn);
    const bg=document.createElement('div');bg.id='accessBg';bg.innerHTML=`<div class="access-modal"><div class="access-head"><div><h2>Pengaturan Hak Akses</h2><div class="access-muted">Dikelola khusus oleh KA IPSRS</div></div><button class="access-btn-secondary" onclick="closeAccessPanel()">Tutup</button></div><div id="accessContent"><div class="access-muted">Memuat...</div></div></div>`;bg.onclick=e=>{if(e.target===bg)closeAccessPanel()};document.body.appendChild(bg);
  }
  async function open(){document.getElementById('accessBg').classList.add('show');await render();}
  window.closeAccessPanel=function(){document.getElementById('accessBg').classList.remove('show');};
  async function render(){
    const el=document.getElementById('accessContent');if(!el)return;el.innerHTML='<div class="access-muted">Memuat pengaturan...</div>';
    try{
      const [ac,st,pm]=await Promise.all([callAccessRead('apiGetAccessControl'),callAccessRead('apiListStaff'),callAccessRead('apiListEditPermissions')]);
      if(!ac.ok)throw new Error(ac.msg||'Gagal memuat pengaturan.');
      staffCache=(st&&st.ok?st.data:[]).filter(x=>x.status!=='Nonaktif');
      const perms=pm&&pm.ok?pm.data:[];
      el.innerHTML=`<div class="access-grid"><div class="access-card"><div class="access-row"><div><h3>Visibilitas Laporan Tim</h3><div class="access-muted">AKTIF = semua anggota IPSRS dapat melihat laporan tim. NONAKTIF = hanya pemilik dan KA IPSRS.</div></div><button class="access-switch ${ac.laporan_tim==='AKTIF'?'on':''}" onclick="toggleAccessSetting('LAPORAN_TIM','${ac.laporan_tim}')"></button></div></div><div class="access-card"><div class="access-row"><div><h3>Administrasi — Izin Edit</h3><div class="access-muted">Pengaturan ini disimpan untuk kompatibilitas konfigurasi. Hak edit aktual ditentukan backend melalui pemilik, KA IPSRS, dan EDIT_PERMISSIONS.</div></div><button class="access-switch ${ac.administrasi_edit==='AKTIF'?'on':''}" onclick="toggleAccessSetting('ADMINISTRASI_EDIT','${ac.administrasi_edit}')"></button></div></div></div><div class="access-card"><h3>Izin Edit Khusus</h3><div class="access-muted">Berikan izin kepada staf tertentu untuk mengedit laporan staf lain. Laporan KA IPSRS tidak dapat diberi izin edit.</div><div class="access-form"><div><label>Pemberi izin</label><select id="permGrantee">${staffCache.map(x=>`<option value="${esc(x.staff_id)}">${esc(x.nama)} — ${esc(x.role_label||x.role)}</option>`).join('')}</select></div><div><label>Target laporan</label><select id="permTarget">${staffCache.map(x=>`<option value="${esc(x.staff_id)}">${esc(x.nama)} — ${esc(x.role_label||x.role)}</option>`).join('')}</select></div><button class="access-btn-primary" onclick="saveAccessPermission()">Simpan Izin</button></div><table class="access-table"><thead><tr><th>Pemberi</th><th>Target</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${perms.length?perms.map(p=>`<tr><td>${esc(p.granted_to_staff_name)}</td><td>${esc(p.target_staff_name)}</td><td>${p.is_active==='AKTIF'?'AKTIF':'NONAKTIF'}</td><td><button class="access-btn-secondary" onclick="togglePermission('${esc(p.granted_to_staff_id)}','${esc(p.target_staff_id)}','${p.is_active}')">${p.is_active==='AKTIF'?'Cabut':'Aktifkan'}</button></td></tr>`).join(''):'<tr><td colspan="4">Belum ada izin khusus.</td></tr>'}</tbody></table></div><div class="access-actions"><button class="access-btn-secondary" onclick="closeAccessPanel()">Selesai</button></div>`;
    }catch(e){el.innerHTML='<div class="access-muted">Gagal memuat: '+esc(e.message||e)+'</div>';}
  }
  window.toggleAccessSetting=async function(key,current){const next=current==='AKTIF'?'NONAKTIF':'AKTIF';if(!confirm('Ubah '+key+' menjadi '+next+'?'))return;const r=await callAccessApi('apiSetAccessSetting',key,next);if(!r.ok)alert(r.msg||'Gagal mengubah pengaturan.');await render();};
  window.saveAccessPermission=async function(){const g=document.getElementById('permGrantee').value,t=document.getElementById('permTarget').value;if(g===t){alert('Pemberi izin dan target harus berbeda.');return;}const r=await callAccessApi('apiSetEditPermission',g,t,true);if(!r.ok)alert(r.msg||'Gagal menyimpan izin.');await render();};
  window.togglePermission=async function(g,t,current){const next=current==='AKTIF'?false:true;const r=await callAccessApi('apiSetEditPermission',g,t,next);if(!r.ok)alert(r.msg||'Gagal mengubah izin.');await render();};
  const timer=setInterval(()=>{mount();if(mounted)clearInterval(timer);},500);setTimeout(mount,50);
})();
