import { withSupabase } from "npm:@supabase/server@1.8.0";
import { createClient } from "npm:@supabase/supabase-js@2.116.0";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const GAS_URL="https://script.google.com/macros/s/AKfycbzC7caqnB_sDXgNV5sW1nKbl4m2JM22qK-zWIx_VQnI4I2icZcLldatvq9UsqMEHf1Z/exec";
function out(b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}})}
function range(month:string){const m=/^\d{4}-\d{2}$/.test(String(month||""))?month:new Date().toISOString().slice(0,7);const [y,mo]=m.split("-").map(Number);return{month:m,start:m+"-01",end:new Date(Date.UTC(y,mo,0)).toISOString().slice(0,10)}}
function label(r:string){return({KA_IPSRS:"KA IPSRS",ADMINISTRASI:"Administrasi IPSRS",KASIE:"Kasie",STAF:"Staf",PETUGAS_SHIFT:"Petugas Shift"} as any)[r]||r}
const SPARE_PART_NEW_CATEGORIES=new Set(["PEMELIHARAAN RUTIN SESUAI JADWAL DENGAN PENGGANTIAN SPARE PART BARU","PEMELIHARAAN DILUAR JADWAL RUTIN DENGAN PENGGANTIAN SPARE PART BARU","PERBAIKAN DENGAN PENGGANTIAN SPARE PART BARU"]);
const UNIT_NEW_CATEGORIES=new Set(["PENGGANTIAN ATAU PEMASANGAN UNIT /ALAT BARU (PERBAIKAN ATAU PASANG BARU)"]);
function normalizeCategory(v:any){return String(v||"").trim().replace(/\s+/g," ").toUpperCase()}
function categoryKind(v:any){const n=normalizeCategory(v);return{spare:SPARE_PART_NEW_CATEGORIES.has(n),unit:UNIT_NEW_CATEGORIES.has(n)}}
function isNewCategory(v:any){const k=categoryKind(v);return k.spare||k.unit}
// PERF 20260923: read paths use short-lived cache + selective payloads; date index added in Supabase migration.
const reportCache=new Map<string,{at:number,value:any}>(); const CACHE_TTL=5000;
const accessSettingCache=new Map<string,{at:number,value:string}>();
const editPermissionCache=new Map<string,{at:number,value:boolean}>();
const reportOwnerRoleCache=new Map<string,{at:number,value:string}>();
const PERMISSION_CACHE_TTL=15000;
const OWNER_ROLE_CACHE_TTL=15000;
function cacheGet(k:string){const x=reportCache.get(k);return x&&Date.now()-x.at<CACHE_TTL?x.value:null}
function cacheSet(k:string,v:any){reportCache.set(k,{at:Date.now(),value:v});return v}
function cacheClear(){reportCache.clear();accessSettingCache.clear();editPermissionCache.clear();reportOwnerRoleCache.clear()}
async function reportOwnerRole(db:any,staffId:string){
 const k=String(staffId||"").trim();
 if(!k)return "";
 const hit=reportOwnerRoleCache.get(k);
 if(hit&&Date.now()-hit.at<OWNER_ROLE_CACHE_TTL)return hit.value;
 const {data,error}=await db.from("staff").select("role,status").eq("staff_id",k).maybeSingle();
 if(error)throw error;
 const value=String(data?.status==="Aktif"?data?.role||"": "").toUpperCase();
 reportOwnerRoleCache.set(k,{at:Date.now(),value});
 return value;
}
function map(r:any,canEdit=false){return{CanEdit:!!canEdit,ID:r.report_id,report_id:r.report_id,StaffID:r.staff_id,Petugas:r.nama_snapshot||r.pelapor||r.created_by_name||r.staff_id,Nama:r.nama_snapshot||r.created_by_name||r.staff_id,Bidang:r.bidang_snapshot||"",Role:r.role_snapshot||"",RoleLabel:label(r.role_snapshot||""),Tanggal:r.tanggal,Pukul:r.pukul,NoLK:r.nolk,Ruang:r.ruang,MasalahKegiatan:r.masalah_kegiatan,Tindakan:r.tindakan,Status:r.status,Keterangan:r.keterangan,Kategori:r.kategori,AreaKerja:r.area_kerja,Item:r.item,SparePartUnit:r.spare_part_unit,Type:r.type,Jumlah:r.jumlah,created_at:r.created_at,updated_at:r.updated_at,created_by_username:r.created_by_username,created_by_staff_id:r.created_by_staff_id,created_by_name:r.created_by_name,created_by_role:r.created_by_role,updated_by_staff_id:r.updated_by_staff_id,updated_by_name:r.updated_by_name,updated_by_role:r.updated_by_role,version:r.version}}
const REPORT_EDITABLE_FIELDS=["Tanggal","Pelapor","Pukul","NoLK","Ruang","MasalahKegiatan","Tindakan","Status","Keterangan","Kategori","AreaKerja","Item","SparePartUnit","Type","Jumlah","JadwalKerja","RencanaKegiatan","TargetPekerjaan","RealisasiPekerjaan","HasilPencapaian","StatusPencapaian","Kendala","TindakLanjut","WaktuMulai","WaktuSelesai"];
async function accessSetting(db:any,key:string,def="NONAKTIF"){
 const k=String(key||"");
 const hit=accessSettingCache.get(k);
 if(hit&&Date.now()-hit.at<PERMISSION_CACHE_TTL)return hit.value;
 const {data,error}=await db.from("access_settings").select("value").eq("key",k).maybeSingle();
 if(error)throw error;
 const value=String(data?.value||def).toUpperCase();
 accessSettingCache.set(k,{at:Date.now(),value});
 return value;
}
function effectivePayload(old:any,p:any){const e:any={Tanggal:old.tanggal,Pelapor:old.pelapor,Pukul:old.pukul,NoLK:old.nolk,Ruang:old.ruang,MasalahKegiatan:old.masalah_kegiatan,Tindakan:old.tindakan,Status:old.status,Keterangan:old.keterangan,Kategori:old.kategori,AreaKerja:old.area_kerja,Item:old.item,SparePartUnit:old.spare_part_unit,Type:old.type,Jumlah:old.jumlah,JadwalKerja:old.jadwal_kerja,RencanaKegiatan:old.rencana_kegiatan,TargetPekerjaan:old.target_pekerjaan,RealisasiPekerjaan:old.realisasi_pekerjaan,HasilPencapaian:old.hasil_pencapaian,StatusPencapaian:old.status_pencapaian,Kendala:old.kendala,TindakLanjut:old.tindak_lanjut,WaktuMulai:old.waktu_mulai,WaktuSelesai:old.waktu_selesai};for(const k of REPORT_EDITABLE_FIELDS)if(Object.prototype.hasOwnProperty.call(p,k))e[k]=p[k];return e;}
function validateReportPayload(p:any){for(const k of ["Kategori","AreaKerja","Item"])if(String(p[k]||"")==="__ADD_NEW__")return k+" belum boleh menggunakan penanda tambah baru.";const miss=["Tanggal","Item"].filter(k=>!String(p[k]??"").trim());if(!String(p.MasalahKegiatan??"").trim()&&!String(p.RealisasiPekerjaan??"").trim())miss.push("MasalahKegiatan atau RealisasiPekerjaan");if(miss.length)return miss[0]+" wajib diisi.";if(isNewCategory(p.Kategori)&&(!String(p.SparePartUnit??"").trim()||!String(p.Type??"").trim()||!String(p.Jumlah??"").trim()))return"Spare Part / Unit, Type, dan Jumlah wajib diisi untuk kategori Spare Part Baru / Unit Baru.";return null;}
async function canViewReport(db:any,s:any,r:any){
 if(!r)return false;
 if(!s||!s.staff_id)return false;
 if(s.role==="KA_IPSRS")return true;
 if(r.staff_id===s.staff_id)return true;
 if(String(r.role_snapshot||"").toUpperCase()==="KA_IPSRS")return false;
 if((await reportOwnerRole(db,r.staff_id))==="KA_IPSRS")return false;
 return (await accessSetting(db,"LAPORAN_TIM","NONAKTIF"))==="AKTIF";
}
async function canEditReport(db:any,s:any,r:any){
 if(!r)return{ok:false,reason:"Laporan tidak ditemukan."};
 if(s.role==="KA_IPSRS")return{ok:true};
 if(r.staff_id===s.staff_id)return{ok:true};
 if(String(r.role_snapshot||"").toUpperCase()==="KA_IPSRS")return{ok:false,reason:"Laporan KA IPSRS hanya dapat diedit oleh KA IPSRS."};
 if((await reportOwnerRole(db,r.staff_id))==="KA_IPSRS")return{ok:false,reason:"Laporan KA IPSRS hanya dapat diedit oleh KA IPSRS."};
 if(s.role==="ADMINISTRASI"){
   if((await accessSetting(db,"ADMINISTRASI_EDIT","NONAKTIF"))==="AKTIF")return{ok:true};
   return{ok:false,reason:"Administrasi tidak memiliki izin edit laporan staf lain saat ADMINISTRASI_EDIT NONAKTIF."};
 }
 const pk=String(s.staff_id||"");
 const hit=editPermissionCache.get(pk);
 let allowed:boolean;
 if(hit&&Date.now()-hit.at<PERMISSION_CACHE_TTL){
   allowed=hit.value;
 }else{
   const {data,error}=await db.from("edit_permissions").select("permission_id").eq("granted_to_staff_id",s.staff_id).eq("is_active",true).limit(1).maybeSingle();
   if(error)throw error;
   allowed=!!data;
   editPermissionCache.set(pk,{at:Date.now(),value:allowed});
 }
 return allowed?{ok:true}:{ok:false,reason:"Anda tidak memiliki hak untuk mengedit laporan ini."};
}
function dbp(p:any){const n=(v:any)=>v===""||v==null?null:Number(v);return{tanggal:p.Tanggal||null,pelapor:p.Pelapor||null,pukul:p.Pukul||null,nolk:p.NoLK||null,ruang:p.Ruang||null,masalah_kegiatan:p.MasalahKegiatan||null,tindakan:p.Tindakan||null,status:p.Status||null,keterangan:p.Keterangan||null,kategori:p.Kategori||null,area_kerja:p.AreaKerja||null,item:p.Item||null,spare_part_unit:p.SparePartUnit||null,type:p.Type||null,jumlah:n(p.Jumlah),jadwal_kerja:p.JadwalKerja||null,rencana_kegiatan:p.RencanaKegiatan||null,target_pekerjaan:p.TargetPekerjaan||null,realisasi_pekerjaan:p.RealisasiPekerjaan||null,hasil_pencapaian:p.HasilPencapaian||null,status_pencapaian:p.StatusPencapaian||null,kendala:p.Kendala||null,tindak_lanjut:p.TindakLanjut||null,waktu_mulai:p.WaktuMulai||null,waktu_selesai:p.WaktuSelesai||null}}
async function staff(ctx:any,req?:Request){let uid=ctx.userClaims?.sub;let email=String(ctx.userClaims?.email||"").toLowerCase();if(!uid&&req){const h=req.headers.get("authorization")||"";const m=h.match(/^Bearer\s+(.+)$/i);if(m){const g=await ctx.supabaseAdmin.auth.getUser(m[1]);if(!g.error&&g.data?.user){uid=g.data.user.id;email=String(g.data.user.email||"").toLowerCase();}}}if(!uid)throw Error("Sesi tidak valid.");let {data,error}=await ctx.supabaseAdmin.from("staff").select("staff_id,nama,jabatan,role,bidang,status,auth_user_id,last_login_at,last_seen_at,last_login_device").eq("auth_user_id",uid).maybeSingle();if(error)throw error;if(!data){const email=String(ctx.userClaims?.email||"").toLowerCase();const local=email.split("@")[0];const staffId=local==="kaipsrs"?"KAIPSRS":local;const r=await ctx.supabaseAdmin.from("staff").select("staff_id,nama,jabatan,role,bidang,status,auth_user_id,last_login_at,last_seen_at,last_login_device").eq("staff_id",staffId).maybeSingle();if(r.error)throw r.error;data=r.data;if(data)await ctx.supabaseAdmin.from("staff").update({auth_user_id:uid}).eq("staff_id",data.staff_id);}if(!data)throw Error("Akun Supabase belum terhubung ke data petugas.");if(String(data.status).toLowerCase()!=="aktif")throw Error("Akun petugas tidak aktif.");return data}
async function audit(db:any,s:any,a:string,id:string,k:string,v:any={}){try{await db.from("audit_log").insert({username:s.staff_id,staff_id:s.staff_id,action:a,report_id:id,keterangan:k,field_changed:v.field_changed||null,old_value:v.old_value??null,new_value:v.new_value??null,version_before:v.version_before??null,version_after:v.version_after??null});}catch(_e){}}
async function act(ctx:any,a:string,d:any,req?:Request){const db=ctx.supabaseAdmin,s=await staff(ctx,req);
if(a==="apiWhoAmI"){await db.from("staff").update({last_seen_at:new Date().toISOString()}).eq("staff_id",s.staff_id);return{ok:true,token:d.token||"",username:s.staff_id,staff_id:s.staff_id,nama:s.nama,role:s.role,bidang:s.bidang,status:s.status,role_label:label(s.role)};}
if(a==="apiRecordLogin"){
 const now=new Date().toISOString();
 const ua=String(req?.headers.get("user-agent")||"").trim().slice(0,500);
 const platform=String(req?.headers.get("sec-ch-ua-platform")||"").replace(/^"|"$/g,"").trim();
 const device=[platform,ua].filter(Boolean).join(" | ").slice(0,500)||"Perangkat tidak diketahui";
 const {error}=await db.from("staff").update({last_login_at:now,last_seen_at:now,last_login_device:device}).eq("staff_id",s.staff_id);
 if(error)throw error;
 await audit(db,s,"LOGIN",null,"Login berhasil",{new_value:device});
 return{ok:true,last_login_at:now};
}
if(a==="apiHeartbeat"){
 const now=new Date().toISOString();
 const {error}=await db.from("staff").update({last_seen_at:now}).eq("staff_id",s.staff_id);
 if(error)throw error;
 return{ok:true,last_seen_at:now};
}
if(a==="apiGetOnlineUsers"){
 if(s.role!=="KA_IPSRS")return{ok:false,msg:"Hanya KA IPSRS yang dapat melihat status online dan login terakhir."};
 const {data,error}=await db.from("staff").select("staff_id,nama,jabatan,role,bidang,status,last_login_at,last_seen_at,last_login_device").eq("status","Aktif").order("nama");
 if(error)throw error;
 const now=Date.now(), threshold=3*60*1000;
 return{ok:true,server_time:new Date(now).toISOString(),online_threshold_seconds:180,data:(data||[]).map((x:any)=>{
   const seen=x.last_seen_at?Date.parse(x.last_seen_at):NaN;
   const online=Number.isFinite(seen)&&(now-seen)<=threshold;
   return{staff_id:x.staff_id,nama:x.nama,jabatan:x.jabatan||"",role:x.role,bidang:x.bidang||"",role_label:label(x.role),online,last_seen_at:x.last_seen_at||null,last_login_at:x.last_login_at||null,last_login_device:x.last_login_device||null};
 }).sort((a:any,b:any)=>{const onlineDiff=Number(b.online)-Number(a.online);if(onlineDiff)return onlineDiff;const aLogin=a.last_login_at?Date.parse(a.last_login_at):NaN;const bLogin=b.last_login_at?Date.parse(b.last_login_at):NaN;if(Number.isFinite(aLogin)||Number.isFinite(bLogin)){if(!Number.isFinite(aLogin))return 1;if(!Number.isFinite(bLogin))return -1;if(bLogin!==aLogin)return bLogin-aLogin;}return String(a.nama||"").localeCompare(String(b.nama||""),"id")})};
}
if(a==="apiLogout"){await db.from("staff").update({last_seen_at:new Date(Date.now()-4*60*1000).toISOString()}).eq("staff_id",s.staff_id);return{ok:true};}
if(a==="apiListStaff"){const {data,error}=await db.from("staff_dropdown").select("staff_id,nama,jabatan,role,bidang,status");if(error)throw error;return{ok:true,data:(data||[]).map((x:any)=>({...x,role_label:label(x.role)}))}}
if(a==="apiGetReports"){const mode=String(d.viewMode||"daftar").toLowerCase()==="saya"?"saya":"daftar",z=range(d.bulan),ck=`reports:${mode}:${z.month}:${d.staffIdFilter||""}:${d.bidangFilter||""}:${s.staff_id}`,hit=cacheGet(ck);if(hit)return hit;let q=db.from("reports").select("report_id,staff_id,nama_snapshot,bidang_snapshot,role_snapshot,tanggal,pelapor,pukul,nolk,ruang,masalah_kegiatan,tindakan,status,keterangan,kategori,area_kerja,item,spare_part_unit,type,jumlah,created_at,updated_at,created_by_username,created_by_staff_id,created_by_name,created_by_role,updated_by_staff_id,updated_by_name,updated_by_role,version").gte("tanggal",z.start).lte("tanggal",z.end).order("tanggal",{ascending:false}).order("pukul",{ascending:false});if(mode==="saya"){q=q.eq("staff_id",s.staff_id);}else if(d.staffIdFilter){q=q.eq("staff_id",d.staffIdFilter);}if(d.bidangFilter)q=q.eq("bidang_snapshot",d.bidangFilter);const {data,error}=await q;if(error)throw error;const visible=[];for(const r of data||[]){if(mode!=="saya"&&(String(r.role_snapshot||"").toUpperCase()==="KA_IPSRS"||String(r.staff_id||"")==="KAIPSRS"))continue;if(await canViewReport(db,s,r)){const ce=await canEditReport(db,s,r);visible.push(map(r,ce.ok));}}return cacheSet(ck,{ok:true,data:visible})}
if(a==="apiGetReportById"){const {data,error}=await db.from("reports").select("*").eq("report_id",d.reportId).maybeSingle();if(error)throw error;if(!data)return{ok:false,msg:"Laporan tidak ditemukan."};if(!(await canViewReport(db,s,data)))return{ok:false,msg:"Anda tidak memiliki akses untuk melihat laporan ini."};const ce=await canEditReport(db,s,data);return{ok:true,data:map(data,ce.ok)}}
if(a==="apiCreateReport"){const p=d.payload||{};const validation=validateReportPayload(p);if(validation)return{ok:false,msg:validation};const id=`RPT${Date.now()}-${crypto.randomUUID().replaceAll("-","").slice(0,6).toUpperCase()}`;const row={...dbp(p),report_id:id,staff_id:s.staff_id,nama_snapshot:s.nama,bidang_snapshot:s.bidang,role_snapshot:s.role,created_by_username:s.staff_id,created_by_staff_id:s.staff_id,created_by_name:s.nama,created_by_role:s.role,version:1};const {data,error}=await db.from("reports").insert(row).select("*").single();if(error)throw error;await audit(db,s,"CREATE_REPORT",id,"Membuat laporan baru",{version_after:1});cacheClear();await db.from("staff").update({last_seen_at:new Date().toISOString()}).eq("staff_id",s.staff_id);return{ok:true,report_id:id,data:map(data,true)}}
if(a==="apiUpdateReport"){const {data:old,error:e}=await db.from("reports").select("*").eq("report_id",d.reportId).maybeSingle();if(e)throw e;if(!old)return{ok:false,msg:"Laporan tidak ditemukan."};const permission=await canEditReport(db,s,old);if(!permission.ok){await audit(db,s,"UPDATE_REPORT_DENIED",d.reportId,permission.reason||"Edit ditolak");return{ok:false,msg:permission.reason}}const effective=effectivePayload(old,d.payload||{});const validation=validateReportPayload(effective);if(validation)return{ok:false,msg:validation};const patch=dbp(effective),v=(old.version||1)+1;const {data:u,error}=await db.from("reports").update({...patch,updated_by_staff_id:s.staff_id,updated_by_name:s.nama,updated_by_role:s.role,version:v}).eq("report_id",d.reportId).select("*").single();if(error)throw error;await db.from("report_history").insert({report_id:d.reportId,edited_by_username:s.staff_id,edited_by_staff_id:s.staff_id,data_before_json:map(old),data_after_json:map(u)});await audit(db,s,"UPDATE_REPORT",d.reportId,old.staff_id===s.staff_id?"Mengubah laporan":`Diedit oleh ${s.role} (${s.nama}), pemilik: ${old.nama_snapshot||old.staff_id}`,{version_before:old.version||1,version_after:v});cacheClear();return{ok:true,msg:"Laporan berhasil diperbarui.",data:map(u,true)}}
if(a==="apiGetReportHistory"){const {data:rr,error:re}=await db.from("reports").select("*").eq("report_id",d.reportId).maybeSingle();if(re)throw re;if(s.role!=="KA_IPSRS"&&s.role!=="ADMINISTRASI")return{ok:false,msg:"Hanya KA IPSRS atau Administrasi yang dapat melihat riwayat perubahan."};if(!rr)return{ok:false,msg:"Laporan tidak ditemukan."};if(!(await canViewReport(db,s,rr)))return{ok:false,msg:"Anda tidak memiliki akses untuk melihat riwayat laporan ini."};const {data,error}=await db.from("report_history").select("*").eq("report_id",d.reportId).order("edited_at",{ascending:false});if(error)throw error;return{ok:true,data:(data||[]).map((h:any)=>({edited_at:h.edited_at,edited_by_username:h.edited_by_username||"-",edited_by_staff_id:h.edited_by_staff_id||"-",before:h.data_before_json||{},after:h.data_after_json||{}}))}}
if(a==="apiGetAuditLog"){if(s.role!=="KA_IPSRS"&&s.role!=="ADMINISTRASI")return{ok:false,msg:"Anda tidak memiliki akses audit log."};if(d.reportId){const {data:rr,error:re}=await db.from("reports").select("report_id,staff_id,role_snapshot").eq("report_id",d.reportId).maybeSingle();if(re)throw re;if(!rr)return{ok:false,msg:"Laporan tidak ditemukan."};if(!(await canViewReport(db,s,rr)))return{ok:false,msg:"Anda tidak memiliki akses audit log laporan ini."};}const {data,error}=await db.from("audit_log").select("*").eq("report_id",d.reportId||null).order("timestamp",{ascending:false});if(error)throw error;return{ok:true,data:data||[]}}
if(a==="apiGetStaffMonitoring"){const z=range(d.bulan),ck=`monitor:${s.staff_id}:${z.month}:${d.tanggal||""}:${d.staffIdFilter||""}`,hit=cacheGet(ck);if(hit)return hit;const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta"}).format(new Date());let tanggal=String(d.tanggal||today);if(!tanggal.startsWith(z.month))tanggal=z.month===today.slice(0,7)?today:z.start;let requiredDays=0;if(z.month<today.slice(0,7))requiredDays=Math.floor((Date.parse(z.end)-Date.parse(z.start))/86400000)+1;else if(z.month===today.slice(0,7))requiredDays=Math.floor((Date.parse(today)-Date.parse(z.start))/86400000)+1;let staffQ=db.from("staff").select("staff_id,nama,jabatan,role,bidang,status").eq("status","Aktif").neq("role","KA_IPSRS").order("nama");if(d.staffIdFilter)staffQ=staffQ.eq("staff_id",d.staffIdFilter);const {data:ss,error:se}=await staffQ;if(se)throw se;const {data:rawReports,error:re}=await db.from("reports").select("staff_id,tanggal,role_snapshot").gte("tanggal",z.start).lte("tanggal",z.end);if(re)throw re;const visibleReports:any[]=[];for(const r of rawReports||[]){if(String(r.role_snapshot||"").toUpperCase()==="KA_IPSRS"||String(r.staff_id||"")==="KAIPSRS")continue;if(await canViewReport(db,s,r))visibleReports.push(r);}const by:any={},todayCount:any={},total:any={};for(const r of visibleReports){(by[r.staff_id]??=new Set()).add(r.tanggal);total[r.staff_id]=(total[r.staff_id]||0)+1;if(r.tanggal===tanggal)todayCount[r.staff_id]=(todayCount[r.staff_id]||0)+1}const result={ok:true,bulan:z.month,tanggal,bulan_berjalan:z.month===today.slice(0,7),hari_wajib_terhitung:requiredDays,data:(ss||[]).map((x:any)=>{const set=by[x.staff_id]||new Set(),done=[...set].filter((day:any)=>day>=z.start&&day<=z.end&&(z.month<today.slice(0,7)||day<=today)).length;let statusHari="BELUM_ISI";if(tanggal>today)statusHari="BELUM_TERJADI";else if(todayCount[x.staff_id])statusHari="SUDAH_ISI";return{staff_id:x.staff_id,nama:x.nama,jabatan:x.jabatan||"",role:x.role,role_label:label(x.role),bidang:x.bidang||"",status:x.status||"Aktif",status_hari_ini:statusHari,laporan_hari_ini:todayCount[x.staff_id]||0,sudah_isi_hari_bulan_ini:done,belum_isi_hari_bulan_ini:Math.max(0,requiredDays-done),total_transaksi_bulan_ini:total[x.staff_id]||0}})};return cacheSet(ck,result)}
if(a==="apiGetStaffDailyStatus"){const z=range(d.bulan),today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta"}).format(new Date());const {data:raw,error}=await db.from("reports").select("*").eq("staff_id",d.staffId).gte("tanggal",z.start).lte("tanggal",z.end).order("tanggal");if(error)throw error;const rr:any[]=[];for(const r of raw||[]){if(String(r.role_snapshot||"").toUpperCase()==="KA_IPSRS"||String(r.staff_id||"")==="KAIPSRS")continue;if(await canViewReport(db,s,r))rr.push(r);}const n=Math.floor((Date.parse(z.end)-Date.parse(z.start))/86400000)+1,cal=[];for(let i=0;i<n;i++){const day=new Date(Date.parse(z.start)+i*86400000).toISOString().slice(0,10),c=(rr||[]).filter((r:any)=>r.tanggal===day).length;cal.push({tanggal:day,status:c?"SUDAH_ISI":day>today?"BELUM_TERJADI":"BELUM_ISI",jumlah:c})}return{ok:true,kalender:cal,laporan:await Promise.all((rr||[]).map(async(r:any)=>map(r,(await canEditReport(db,s,r)).ok)))}}
if(a==="apiGetMonthlyRecap"){const z=range(d.bulan),ck=`monthly:${s.staff_id}:${z.month}`,hit=cacheGet(ck);if(hit)return hit;const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta"}).format(new Date()),eff=z.month===today.slice(0,7)?today:z.end;let staffQ=db.from("staff").select("staff_id,nama,jabatan,role,bidang,status").eq("status","Aktif").neq("role","KA_IPSRS").order("staff_id");if(d.staffIdFilter)staffQ=staffQ.eq("staff_id",d.staffIdFilter);const {data:ss,error:se}=await staffQ;if(se)throw se;const {data:rawReports,error:re}=await db.from("reports").select("staff_id,tanggal,bidang_snapshot,role_snapshot").gte("tanggal",z.start).lte("tanggal",eff);if(re)throw re;const visibleReports:any[]=[];for(const r of rawReports||[])if(await canViewReport(db,s,r))visibleReports.push(r);const req=Math.floor((Date.parse(eff)-Date.parse(z.start))/86400000)+1,sets:any={},tx:any={};for(const x of ss||[])sets[x.staff_id]=new Set();for(const r of visibleReports){(sets[r.staff_id]??=new Set()).add(r.tanggal);tx[r.staff_id]=(tx[r.staff_id]||0)+1}const bm:any={},per=(ss||[]).map((x:any)=>{const n=(sets[x.staff_id]||new Set()).size,k=x.bidang||"-";(bm[k]??={bidang:k,jumlah_staf:0,hari_isi:0,total_transaksi:0});bm[k].jumlah_staf++;bm[k].hari_isi+=n;bm[k].total_transaksi+=tx[x.staff_id]||0;return{...x,role_label:label(x.role),sudah_isi_hari_bulan_ini:n,belum_isi_hari_bulan_ini:Math.max(0,req-n),total_transaksi_bulan_ini:tx[x.staff_id]||0}}),tot=per.reduce((a:number,x:any)=>a+x.sudah_isi_hari_bulan_ini,0),required=(ss||[]).length*req;return cacheSet(ck,{ok:true,bulan:z.month,per_staff:per,per_bidang:Object.values(bm).sort((a:any,b:any)=>String(a.bidang).localeCompare(String(b.bidang))),ringkasan:{total_staff:(ss||[]).length,total_hari_wajib:required,total_staff_days_wajib:required,total_staff_days_sudah_isi:tot,total_staff_days_belum_isi:Math.max(0,required-tot),persentase_kepatuhan:required?Math.round((tot/required)*1000)/10:0,total_transaksi:(visibleReports||[]).length}})}
if(a==="apiDashboardStats"){
 const z=range(d.bulan),ck=`dash:${z.month}:${d.staffIdFilter||""}:${d.bidangFilter||""}:${s.staff_id}`,hit=cacheGet(ck);if(hit)return hit;
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta"}).format(new Date());
 const dashboardTanggal=z.month===today.slice(0,7)?today:z.start;
 let staffQ=db.from("staff").select("staff_id,nama,role,bidang,status").eq("status","Aktif").neq("role","KA_IPSRS").order("nama");if(d.staffIdFilter)staffQ=staffQ.eq("staff_id",d.staffIdFilter);if(d.bidangFilter)staffQ=staffQ.eq("bidang",d.bidangFilter);const {data:activeStaff,error:staffErr}=await staffQ;if(staffErr)throw staffErr;
 let q=db.from("reports").select("report_id,staff_id,nama_snapshot,bidang_snapshot,role_snapshot,tanggal,pukul,ruang,masalah_kegiatan,tindakan,status,keterangan,kategori,area_kerja,item,spare_part_unit,type,jumlah,status_pencapaian,created_at").gte("tanggal",z.start).lte("tanggal",z.end);
 if(d.staffIdFilter)q=q.eq("staff_id",d.staffIdFilter);
 if(d.bidangFilter)q=q.eq("bidang_snapshot",d.bidangFilter);
 const {data:rawReports,error}=await q;if(error)throw error;
 const rr:any[]=[];for(const r of rawReports||[])if(await canViewReport(db,s,r))rr.push(r);
 const total=rr?.length||0,sel=(rr||[]).filter((r:any)=>r.status==="Selesai").length,bel=total-sel,cat:any={},ar:any={},sm:any={},pc:any={};for(const st of activeStaff||[])sm[st.staff_id]={staff_id:st.staff_id,nama:st.nama,role:st.role,bidang:st.bidang||"",value:0};let spare=0,unit=0;
 for(const r of rr||[]){if(r.kategori){cat[r.kategori]=(cat[r.kategori]||0)+1;const kind=categoryKind(r.kategori);if(kind.spare)spare++;if(kind.unit)unit++;}if(r.area_kerja)ar[r.area_kerja]=(ar[r.area_kerja]||0)+1;const k=r.staff_id;if(sm[k])sm[k].value++;const p=r.status_pencapaian||r.status||"Belum Diisi";pc[p]=(pc[p]||0)+1}
 const recentSource=(rr||[]).filter((r:any)=>String(r.role_snapshot||"").toUpperCase()!=="KA_IPSRS" && String(r.staff_id||"")!=="KAIPSRS");const recent=await Promise.all(recentSource.slice().sort((a:any,b:any)=>String(b.report_id).localeCompare(String(a.report_id))).slice(0,6).map(async(r:any)=>map(r,(await canEditReport(db,s,r)).ok)));
 const todayCount:any={};for(const r of rr||[])if(r.tanggal===dashboardTanggal)todayCount[r.staff_id]=(todayCount[r.staff_id]||0)+1;
 const monitoringToday=(activeStaff||[]).map((x:any)=>({staff_id:x.staff_id,nama:x.nama,jabatan:x.jabatan||"",role:x.role,role_label:label(x.role),bidang:x.bidang||"",status:x.status||"Aktif",status_hari_ini:todayCount[x.staff_id]?"SUDAH_ISI":"BELUM_ISI",laporan_hari_ini:todayCount[x.staff_id]||0}));
 const sortCount=(a:any,b:any)=>Number(b.value||0)-Number(a.value||0)||String(a.label||"").localeCompare(String(b.label||""),"id");const kategori=Object.entries(cat).map(([label,value])=>({label,value})).sort(sortCount);const area=Object.entries(ar).map(([label,value])=>({label,value})).sort(sortCount);const staff=Object.values(sm).sort((a:any,b:any)=>Number(b.value||0)-Number(a.value||0)||String(a.nama||a.staff_id||"").localeCompare(String(b.nama||b.staff_id||""),"id"));return cacheSet(ck,{ok:true,data:{total,selesai:sel,belum:bel,persen:total?Math.round(sel/total*100):0,kategori,area,staff,recent,pencapaian:pc,spare_part_baru:spare,unit_baru:unit,monitoring_today:{tanggal:dashboardTanggal,data:monitoringToday}}})
}
if(a==="apiGetStaffReports"){const z=range(d.bulan),{data,error}=await db.from("reports").select("*").eq("staff_id",d.staffId).gte("tanggal",z.start).lte("tanggal",z.end);if(error)throw error;const visible:any[]=[];for(const r of data||[]){if(String(r.role_snapshot||"").toUpperCase()==="KA_IPSRS"||String(r.staff_id||"")==="KAIPSRS")continue;if(await canViewReport(db,s,r))visible.push(r);}return{ok:true,data:await Promise.all(visible.map(async(r:any)=>map(r,(await canEditReport(db,s,r)).ok)))}}
if(a==="apiGetStaffPerformance"){const z=range(d.bulan),{data,error}=await db.from("reports").select("*").eq("staff_id",d.staffId).gte("tanggal",z.start).lte("tanggal",z.end);if(error)throw error;const rr:any[]=[];for(const r of data||[]){if(String(r.role_snapshot||"").toUpperCase()==="KA_IPSRS"||String(r.staff_id||"")==="KAIPSRS")continue;if(await canViewReport(db,s,r))rr.push(r);}const n=rr.length,sx=rr.filter((r:any)=>r.status==="Selesai").length;return{ok:true,data:{staff_id:d.staffId,total:n,selesai:sx,belum:n-sx,persentase:n?Math.round(sx/n*100):0}}}
if(a==="apiGetKategoriKustom"){const {data,error}=await db.from("master_data").select("name").eq("data_type","KATEGORI").gte("id",695).eq("is_active",true).order("id");if(error)throw error;return{ok:true,kategori:(data||[]).map((x:any)=>x.name).sort((a:any,b:any)=>String(a).localeCompare(String(b),"id"))}}
if(a==="apiGetAreaKerjaKustom"){const {data,error}=await db.from("master_data").select("name").eq("data_type","AREA").gte("id",700).eq("is_active",true).order("id");if(error)throw error;return{ok:true,area:(data||[]).map((x:any)=>x.name).sort((a:any,b:any)=>String(a).localeCompare(String(b),"id"))}}
if(a==="apiGetItemKustom"){const {data,error}=await db.from("master_data").select("name,parent_id").eq("data_type","ITEM").gte("id",707).eq("is_active",true).order("id");if(error)throw error;const {data:aa,error:ae}=await db.from("master_data").select("id,name").eq("data_type","AREA");if(ae)throw ae;const nm:any={};for(const x of aa||[])nm[x.id]=x.name;const items:any={};for(const x of data||[]){const area=nm[x.parent_id];if(area)(items[area]??=[]).push(x.name)}return{ok:true,items}}
if(a==="apiTambahKategori"){const n=String(d.nama||"").trim();if(!n)return{ok:false,msg:"Nama kategori wajib diisi."};if(n.length>120)return{ok:false,msg:"Nama kategori maksimal 120 karakter."};const norm=(v:any)=>String(v||"").trim().toLocaleLowerCase("id");const staticList=Array.isArray(d.staticList)?d.staticList:[];if(staticList.some((x:any)=>norm(x)===norm(n)))return{ok:false,msg:"Kategori sudah ada."};const {data:dup}=await db.from("master_data").select("id").eq("data_type","KATEGORI").ilike("name",n).limit(1);if((dup||[]).length)return{ok:false,msg:"Kategori sudah ada."};const {data,error}=await db.from("master_data").insert({data_type:"KATEGORI",name:n,sort_order:999,is_active:true,created_by:ctx.userClaims.sub}).select("name").single();if(error)throw error;return{ok:true,kategori:error?null:data.name}}
if(a==="apiTambahAreaKerja"){const n=String(d.nama||"").trim();if(!n)return{ok:false,msg:"Nama area kerja wajib diisi."};if(n.length>120)return{ok:false,msg:"Nama area kerja maksimal 120 karakter."};const norm=(v:any)=>String(v||"").trim().toLocaleLowerCase("id");const staticList=Array.isArray(d.staticList)?d.staticList:[];if(staticList.some((x:any)=>norm(x)===norm(n)))return{ok:false,msg:"Area kerja sudah ada."};const {data:dup}=await db.from("master_data").select("id").eq("data_type","AREA").ilike("name",n).limit(1);if((dup||[]).length)return{ok:false,msg:"Area kerja sudah ada."};const {data,error}=await db.from("master_data").insert({data_type:"AREA",name:n,sort_order:999,is_active:true,created_by:ctx.userClaims.sub}).select("name").single();if(error)throw error;return{ok:true,area:data.name}}
if(a==="apiTambahItem"){const ar=String(d.area||"").trim(),n=String(d.nama||"").trim();if(!ar||!n)return{ok:false,msg:"Area dan nama item wajib diisi."};if(n.length>120)return{ok:false,msg:"Nama item maksimal 120 karakter."};const norm=(v:any)=>String(v||"").trim().toLocaleLowerCase("id");const existingItemsForArea=Array.isArray(d.existingItemsForArea)?d.existingItemsForArea:[];if(existingItemsForArea.some((x:any)=>norm(x)===norm(n)))return{ok:false,msg:"Item sudah ada pada area tersebut."};const {data:a1}=await db.from("master_data").select("id").eq("data_type","AREA").eq("name",ar).maybeSingle();if(!a1)return{ok:false,msg:"Area kerja tidak ditemukan."};const {data:dup}=await db.from("master_data").select("id").eq("data_type","ITEM").eq("parent_id",a1.id).ilike("name",n).limit(1);if((dup||[]).length)return{ok:false,msg:"Item sudah ada pada area tersebut."};const {data,error}=await db.from("master_data").insert({data_type:"ITEM",parent_id:a1.id,name:n,sort_order:999,is_active:true,created_by:ctx.userClaims.sub}).select("name").single();if(error)throw error;return{ok:true,item:data.name}}
if(a==="apiGetAccessControl"){if(s.role!=="KA_IPSRS"&&s.role!=="ADMINISTRASI")return{ok:false,msg:"Tidak memiliki akses pengaturan."};const {data,error}=await db.from("access_settings").select("key,value");if(error)throw error;const o:any={};for(const x of data||[])o[String(x.key).toLowerCase()]=x.value;const {data:ep,error:ee}=await db.from("edit_permissions").select("permission_id").eq("granted_to_staff_id",s.staff_id).eq("is_active",true).limit(1).maybeSingle();if(ee)throw ee;return{ok:true,laporan_tim:o.laporan_tim||"AKTIF",administrasi_edit:o.administrasi_edit||"NONAKTIF",has_edit_permission:!!ep}}
if(a==="apiListEditPermissions"){if(s.role!=="KA_IPSRS")return{ok:false,msg:"Hanya KA IPSRS yang dapat melihat izin edit."};const {data,error}=await db.from("edit_permissions").select("*").order("created_at",{ascending:false});if(error)throw error;return{ok:true,data:data||[]}}
if(a==="apiSetAccessSetting"){if(s.role!=="KA_IPSRS")return{ok:false,msg:"Hanya KA IPSRS yang dapat mengubah pengaturan."};const key=String(d.key||"").trim(),value=String(d.value||"").trim();if(!["LAPORAN_TIM","ADMINISTRASI_EDIT"].includes(key)||!["AKTIF","NONAKTIF"].includes(value))return{ok:false,msg:"Pengaturan tidak valid."};const {error}=await db.from("access_settings").upsert({key,value,updated_at:new Date().toISOString(),updated_by_staff_id:s.staff_id,updated_by_name:s.nama},{onConflict:"key"});if(error)throw error;return{ok:true}}
if(a==="apiSetEditPermission"){if(s.role!=="KA_IPSRS")return{ok:false,msg:"Hanya KA IPSRS yang dapat mengubah izin."};const g=String(d.grantedToStaffId||"").trim(),t=String(d.targetStaffId||"").trim(),active=!!d.isActive;if(!g||!t||g===t)return{ok:false,msg:"Pemberi dan target harus berbeda."};const {data:target}=await db.from("staff").select("staff_id,nama,role").eq("staff_id",t).maybeSingle();if(!target)return{ok:false,msg:"Target petugas tidak ditemukan."};if(target.role==="KA_IPSRS")return{ok:false,msg:"Laporan KA IPSRS tidak dapat diberi izin edit."};const {data:grant}=await db.from("staff").select("staff_id,nama").eq("staff_id",g).maybeSingle();if(!grant)return{ok:false,msg:"Pemberi izin tidak ditemukan."};const {data:existing,error:existingError}=await db.from("edit_permissions").select("permission_id").eq("granted_to_staff_id",g).eq("target_staff_id",t).limit(1).maybeSingle();if(existingError)throw existingError;const now=new Date().toISOString();if(existing?.permission_id){const {error}=await db.from("edit_permissions").update({granted_to_staff_name:grant.nama,target_staff_name:target.nama,is_active:active,granted_by_staff_id:s.staff_id,granted_by_name:s.nama,updated_at:now}).eq("permission_id",existing.permission_id);if(error)throw error;}else{const permission_id="PERM-"+crypto.randomUUID().replaceAll("-","").slice(0,8).toUpperCase();const {error}=await db.from("edit_permissions").insert({permission_id,granted_to_staff_id:g,granted_to_staff_name:grant.nama,target_staff_id:t,target_staff_name:target.nama,is_active:active,granted_by_staff_id:s.staff_id,granted_by_name:s.nama,created_at:now,updated_at:now});if(error)throw error;}return{ok:true}}
if(a==="apiAdminResetPassword"){if(s.role!=="KA_IPSRS"&&s.role!=="ADMINISTRASI")return{ok:false,msg:"Tidak memiliki hak reset password."};const target=String(d.staffId||"").trim(),newp=String(d.newPassword||"");if(!target||newp.length<6)return{ok:false,msg:"Staff dan password baru wajib diisi; minimal 6 karakter."};const {data:ts,error:te}=await db.from("staff").select("staff_id,auth_user_id,role").eq("staff_id",target).maybeSingle();if(te)throw te;if(!ts?.auth_user_id)return{ok:false,msg:"Akun Auth target belum terhubung."};if(s.role==="ADMINISTRASI"&&ts.role==="KA_IPSRS")return{ok:false,msg:"Administrasi tidak dapat reset password KA IPSRS."};const {error}=await db.auth.admin.updateUserById(ts.auth_user_id,{password:newp});if(error)throw error;await audit(db,s,"ADMIN_RESET_PASSWORD",null,"Reset password petugas",{new_value:target});return{ok:true,msg:"Password petugas berhasil direset."}}if(a==="apiChangePassword"){const oldp=String(d.oldPassword||""),newp=String(d.newPassword||"");if(newp.length<6)return{ok:false,msg:"Password baru minimal 6 karakter."};const {data:u,error:ue}=await db.auth.admin.getUserById(authUid);if(ue||!u?.user?.email)return{ok:false,msg:"Akun Auth tidak ditemukan."};const pub=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}")["default"];const ac=createClient(Deno.env.get("SUPABASE_URL")!,pub,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {error:oe}=await ac.auth.signInWithPassword({email:u.user.email,password:oldp});if(oe)return{ok:false,msg:"Password lama salah."};const {error}=await db.auth.admin.updateUserById(ctx.userClaims.sub,{password:newp});if(error)throw error;return{ok:true,msg:"Password berhasil diganti."}}
await db.from("staff").update({last_seen_at:new Date().toISOString()}).eq("staff_id",s.staff_id);return{ok:false,msg:"Action API tidak dikenal: "+a}}
export default{fetch:withSupabase({auth:"user"},async(req,ctx)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const b=await req.json();return out(await act(ctx,b.action,b.data||{},req))}catch(e:any){console.error(e);return out({ok:false,msg:e?.message||"Terjadi kesalahan server."},400)}})};