function apiLogin(username,password){try{setupDatabase();return login(username,password);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiLogout(token){try{return logout(token);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiWhoAmI(token){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return {ok:true,username:s.username,staff_id:s.staff_id,nama:s.nama,bidang:s.bidang,shift:s.shift,role:s.role,role_label:ROLE_LABELS[s.role]||s.role};}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiCreateReport(token,payload){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return createReport(s,payload||{});}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetReports(token,bulan,staffIdFilter,bidangFilter,shiftFilter){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return getReports(s,bulan||'',staffIdFilter||null,bidangFilter||null,shiftFilter||null);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiUpdateReport(token,reportId,payload){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return updateReport(s,reportId,payload||{});}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetReportHistory(token,reportId){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return getReportHistory(s,reportId);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiListStaff(token){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return listStaff(s);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiChangePassword(token,oldPassword,newPassword){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return changePassword(s,oldPassword,newPassword);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiDashboardStats(token,bulan,staffIdFilter,bidangFilter,shiftFilter){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return getDashboardStats(s,bulan||'',staffIdFilter||null,bidangFilter||null,shiftFilter||null);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetStaffMonitoring(token,bulan,tanggal){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return getStaffMonitoring(s,bulan||'',tanggal||'');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetStaffDailyStatus(token,staffId,bulan){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return getStaffDailyStatus(s,staffId,bulan||'');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetMonthlyRecap(token,bulan){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return getMonthlyRecap(s,bulan||'');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetAuditLog(token,reportId){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};if(s.role!==ROLE_KA_IPSRS&&s.role!==ROLE_ADMINISTRASI)return {ok:false,msg:'Hanya KA IPSRS atau Administrasi yang dapat melihat audit log.'};return getAuditLogForReport(reportId||'');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetStaffReports(token,staffId,bulan){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return getStaffReports(s,staffId,bulan||'');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetStaffPerformance(token,staffId,bulan){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return getStaffPerformance(s,staffId,bulan||'');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
