function apiLogin(username,password){try{setupDatabase();return login(username,password);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiLogout(token){try{return logout(token);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiWhoAmI(token){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return {ok:true,username:s.username,staff_id:s.staff_id,nama:s.nama,bidang:s.bidang,shift:s.shift,role:s.role,role_label:ROLE_LABELS[s.role]||s.role};}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiCreateReport(token,payload){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return createReport(s,payload||{});}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetReports(token,bulan,staffIdFilter,bidangFilter,shiftFilter){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};if(s.role!==ROLE_KA_IPSRS&&getAccessSetting_(ACCESS_SETTING_LAPORAN_TIM,ACCESS_ACTIVE)!==ACCESS_ACTIVE&&String(staffIdFilter||'')!==String(s.staff_id))return {ok:true,data:[]};if(s.role!==ROLE_KA_IPSRS&&String(staffIdFilter||'')===String(s.staff_id))staffIdFilter=s.staff_id;return getReports(s,bulan||'',staffIdFilter||null,bidangFilter||null,shiftFilter||null);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiUpdateReport(token,reportId,payload){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};const permission=canEditReportById_(s,reportId||'');if(!permission.ok||!permission.owner)return {ok:false,msg:permission.msg||'Laporan tidak ditemukan.'};if(!permission.ok)return {ok:false,msg:'Anda tidak memiliki izin mengedit laporan ini.'};return updateReport(s,reportId,payload||{});}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetReportHistory(token,reportId){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return getReportHistory(s,reportId);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiListStaff(token){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};if(!isManagementRole_(s.role))return {ok:false,msg:'Akses ditolak.'};return listStaff(s);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiChangePassword(token,oldPassword,newPassword){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return changePassword(s,oldPassword,newPassword);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiDashboardStats(token,bulan,staffIdFilter,bidangFilter,shiftFilter){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};if(s.role!==ROLE_KA_IPSRS&&getAccessSetting_(ACCESS_SETTING_LAPORAN_TIM,ACCESS_ACTIVE)!==ACCESS_ACTIVE)staffIdFilter=s.staff_id;return getDashboardStats(s,bulan||'',staffIdFilter||null,bidangFilter||null,shiftFilter||null);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetStaffMonitoring(token,bulan,tanggal){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};if(!isManagementRole_(s.role))return {ok:false,msg:'Akses ditolak.'};return getStaffMonitoring(s,bulan||'',tanggal||'');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetStaffDailyStatus(token,staffId,bulan){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};if(s.role!==ROLE_KA_IPSRS&&String(staffId||'')!==String(s.staff_id)&&getAccessSetting_(ACCESS_SETTING_LAPORAN_TIM,ACCESS_ACTIVE)!==ACCESS_ACTIVE)return {ok:false,msg:'Laporan tim sedang tidak dipublikasikan.'};if(s.role!==ROLE_KA_IPSRS&&String(staffId||'')!==String(s.staff_id)&&!isManagementRole_(s.role))staffId=s.staff_id;return getStaffDailyStatus(s,staffId||s.staff_id,bulan||'');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetMonthlyRecap(token,bulan){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};if(!isManagementRole_(s.role))return {ok:false,msg:'Akses ditolak.'};return getMonthlyRecap(s,bulan||'');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetAuditLog(token,reportId){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};if(s.role!==ROLE_KA_IPSRS&&s.role!==ROLE_ADMINISTRASI)return {ok:false,msg:'Hanya KA IPSRS atau Administrasi yang dapat melihat audit log.'};return getAuditLogForReport(reportId||'');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetStaffReports(token,staffId,bulan){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};if(s.role!==ROLE_KA_IPSRS&&String(staffId||'')!==String(s.staff_id)&&getAccessSetting_(ACCESS_SETTING_LAPORAN_TIM,ACCESS_ACTIVE)!==ACCESS_ACTIVE)return {ok:false,msg:'Laporan tim sedang tidak dipublikasikan.'};if(s.role!==ROLE_KA_IPSRS&&String(staffId||'')!==String(s.staff_id)&&!isManagementRole_(s.role))staffId=s.staff_id;return getStaffReports(s,staffId||s.staff_id,bulan||'');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetStaffPerformance(token,staffId,bulan){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};if(s.role!==ROLE_KA_IPSRS&&String(staffId||'')!==String(s.staff_id)&&getAccessSetting_(ACCESS_SETTING_LAPORAN_TIM,ACCESS_ACTIVE)!==ACCESS_ACTIVE)return {ok:false,msg:'Laporan tim sedang tidak dipublikasikan.'};if(s.role!==ROLE_KA_IPSRS&&String(staffId||'')!==String(s.staff_id)&&!isManagementRole_(s.role))staffId=s.staff_id;return getStaffPerformance(s,staffId||s.staff_id,bulan||'');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetAccessControl(token){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return getAccessControl_(s);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiSetAccessSetting(token,key,value){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return setAccessSetting_(s,key,value);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiListEditPermissions(token){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return listEditPermissions_(s);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiSetEditPermission(token,grantedToStaffId,targetStaffId,isActive){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return setEditPermission_(s,grantedToStaffId,targetStaffId,isActive);}catch(err){return {ok:false,msg:'Error server: '+err.message};}}

function isManagementRole_(role){return role===ROLE_KA_IPSRS||role===ROLE_ADMINISTRASI||role===ROLE_KASIE;}

function apiGetKategoriKustom(token){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return {ok:true,kategori:getCustomNames_(SHEET_KATEGORI_CUSTOM,'nama')};}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetAreaKerjaKustom(token){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return {ok:true,area:getCustomNames_(SHEET_AREA_KERJA_CUSTOM,'nama')};}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiGetItemKustom(token){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};const sheet=getSheet(SHEET_ITEM_CUSTOM),rows=sheet.getDataRange().getValues(),headers=rows[0]||[],areaIdx=headers.indexOf('area'),namaIdx=headers.indexOf('nama'),items={};for(let i=1;i<rows.length;i++){const area=(areaIdx>-1?rows[i][areaIdx]:'').toString().trim(),nama=(namaIdx>-1?rows[i][namaIdx]:'').toString().trim();if(!area||!nama)continue;if(!items[area])items[area]=[];if(items[area].indexOf(nama)===-1)items[area].push(nama);}Object.keys(items).forEach(function(a){items[a].sort(function(x,y){return x.localeCompare(y,'id');});});return {ok:true,items:items};}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiTambahKategori(token,nama,staticList){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return addCustomName_(s,SHEET_KATEGORI_CUSTOM,'nama',nama,staticList||[],'kategori');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiTambahAreaKerja(token,nama,staticList){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};return addCustomName_(s,SHEET_AREA_KERJA_CUSTOM,'nama',nama,staticList||[],'area');}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function apiTambahItem(token,area,nama,existingItemsForArea){try{const s=validateSession(token);if(!s)return {ok:false,msg:'Sesi tidak valid, silakan login kembali.'};area=(area||'').toString().trim();nama=(nama||'').toString().trim();if(!area)return {ok:false,msg:'Area kerja wajib dipilih.'};if(!nama)return {ok:false,msg:'Nama item wajib diisi.'};if(nama.length>120)return {ok:false,msg:'Nama item terlalu panjang (maksimal 120 karakter).'};const sheet=getSheet(SHEET_ITEM_CUSTOM),rows=sheet.getDataRange().getValues(),headers=rows[0]||[],areaIdx=headers.indexOf('area'),namaIdx=headers.indexOf('nama'),existing={};for(let i=1;i<rows.length;i++){const a=(areaIdx>-1?rows[i][areaIdx]:'').toString().trim(),n=(namaIdx>-1?rows[i][namaIdx]:'').toString().trim();if(a===area&&n)existing[n.toLowerCase()]=true;}if(existing[nama.toLowerCase()])return {ok:false,msg:'Item tersebut sudah ada untuk area kerja ini.'};sheet.appendRow([area,nama,nowIso(),s.staff_id,s.nama]);return {ok:true,item:nama};}catch(err){return {ok:false,msg:'Error server: '+err.message};}}
function getCustomNames_(sheetName,nameColumn){const sheet=getSheet(sheetName),rows=sheet.getDataRange().getValues(),headers=rows[0]||[],idx=headers.indexOf(nameColumn),out=[];if(idx<0)return out;for(let i=1;i<rows.length;i++){const value=(rows[i][idx]||'').toString().trim();if(value&&out.indexOf(value)===-1)out.push(value);}out.sort(function(a,b){return a.localeCompare(b,'id');});return out;}
function addCustomName_(session,sheetName,nameColumn,nama,staticList,resultKey){nama=(nama||'').toString().trim();if(!nama)return {ok:false,msg:'Nama wajib diisi.'};if(nama.length>120)return {ok:false,msg:'Nama terlalu panjang (maksimal 120 karakter).'};const normalized=nama.toLowerCase();const staticExists=(staticList||[]).some(function(v){return (v||'').toString().trim().toLowerCase()===normalized;});if(staticExists)return {ok:false,msg:'Nama tersebut sudah ada di data bawaan.'};const existing=getCustomNames_(sheetName,nameColumn);if(existing.some(function(v){return v.toLowerCase()===normalized;}))return {ok:false,msg:'Nama tersebut sudah ada.'};getSheet(sheetName).appendRow([nama,nowIso(),session.staff_id,session.nama]);const out={ok:true};out[resultKey]=nama;return out;}
